# Generated by Django 3.0.8 on 2020-08-05 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='elan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cixis_yeri', models.CharField(max_length=150)),
                ('catma_yeri', models.CharField(max_length=150)),
                ('cixis_vaxti', models.DateField()),
                ('catma_vaxti', models.DateField()),
                ('elaqe_nomresi', models.IntegerField()),
                ('sirket', models.CharField(blank=True, max_length=100, null=True)),
                ('elave_melumatlar', models.TextField(blank=True, null=True)),
                ('silinme_vaxti', models.DateField()),
                ('favorit', models.ManyToManyField(blank=True, related_name='favorit', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='paylasan')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
