# Generated by Django 3.0.8 on 2020-08-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elan',
            name='silinme_vaxti',
            field=models.DateTimeField(),
        ),
    ]
